### ISSUE TITLE
Invalid mutated SELFIES

### ISSUE THREAD

**Issue by whitead** [aspuru-guzik-group/stoned-selfies#2]
In the STONED paper, it is said that "Every one of these mutated SELFIES corresponds to a valid molecule." Yet in the code there is a loop checking for an output SMILES of "". I'm curious what would cause a SELFIES molecule to be invalid? Is this code unnecessary?

**Comment by robpollice** [comment]
It depends on which specific piece of code you refer to. One thing that can happen is that there is a SELFIES with only one character and the mutation function decides to remove that character which would provide an empty SELFIES as it is not checked whether remove character is allowed. We could explicitly check for that to avoid a global check. Apart from that, it is simply a case of finding potential bugs in the current SELFIES code as we keep track of cases that failed.

**Comment by whitead** [comment]
Got it, thanks for the explanation!
