### ISSUE TITLE
Invalid valence of generated molecules

### ISSUE THREAD

**Issue by Lydia-bka** [aspuru-guzik-group/stoned-selfies#3]
Hi,
Thanks for this Robust Molecule Generation Selfies Tool.
I am having a problem generating molecules with "abnormal" valences having a charged radical atom. I send you these 4 examples  of a molecule having an atom:
1) a radical N+ :                     [N+]N(C(=C[N+](=O)[O-])C[O-])[N+](=O)[O-]
2) a radical O+ :                    O=[N+]([O-])O[O+]c1nonc1C[O-]
3) a radical C- :                     O=[N+]([O-])C=NN=c1nc([N+](=O)[C-]O)[nH][nH]1
4) a O+ with 3 bonds:            O=[N+]([O-])c1nnc2nc([O+]([O-])O)[nH]n12
Selfies is supposed to generate 100% valid molecules, how can we avoid this kind of molecules please?

Best regards,
Lydia
![RadicalN+](https://user-images.githubusercontent.com/102677284/170970645-670d7931-d410-4fc2-98de-5bd9649d05c0.png)
![RadicalO+](https://user-images.githubusercontent.com/102677284/170970782-90883984-4955-4161-bb94-1eafbd4ce1cc.png)
![RadicalC-](https://user-images.githubusercontent.com/102677284/170970099-10401ef3-c64a-42a6-942e-c1e820278e65.png)
![O+3bonds](https://user-images.githubusercontent.com/102677284/170970301-6198a443-9cdb-489c-a442-3ac31770aabf.png)

**Comment by robpollice** [comment]
Hi,
thank you for your interest in our code. I agree with you that these are not standard molecules. However, at least in terms of valence, these are all formally correct structures. If you want to get rid of them, the easiest is to filter out all radicals, for instance with the rdkit function `rdkit.Chem.Descriptors.NumRadicalElectrons(mol)`. For the O+ with three bonds, you could use a SMARTS pattern. Avoiding the generation of these molecules is a bit more involved as it would require to define your own SELFIES alphabet. I hope this is helpful.
Best regards,
Robert

**Comment by Lydia-bka** [comment]
Hi Robert,

Thank you for your help. 
It solves my 2 problems by filtering out the radicals, and set the semantic bond_constraints['O+'] = 2 with the sf.set_semantic_constraints function.

Best regards,
Lydia
