### ISSUE TITLE
Define our own SELFIES alphabet for mutations

### ISSUE THREAD

**Issue by Lydia-bka** [aspuru-guzik-group/stoned-selfies#4]
Hi,
Is it possible to restrain the SELFIES alphabet to perform mutations with well defined elements. For example if we want to generate molecules containing only the elements (C, H, O, Cl)?

Best regards,
Lydia

**Comment by akshat998** [comment]
Hi Lydia, 
Yes -- this should be possible! 
When performing mutations with stoned-selfies using function 'mutate_selfie', you could change the line: 
`        alphabet = list(selfies.get_semantic_robust_alphabet()) # 34 SELFIE characters 
`to a list of alphabets that correspond to (C, H, O, Cl). For instance, you could use: 
`        alphabet = ['[Branch1_3]',  '[O]',  '[Ring1]', '[Branch3_3]', '[Branch2_2]', '[Branch2_3]', '[Cl]', '[=C]',  '[Hexpl]', '[Branch2_1]', '[=O]', '[Branch3_2]',  '[Branch1_1]', '[Branch1_2]', '[Ring2]',  '[#C]',  '[Ring3]']
`
The Branch & Ring symbols are needed to create Cycles & chains. 
Hope this helps :) 

Akshat

**Comment by Lydia-bka** [comment]
Hi Akshat,
Thank you for your answer.

When I run alphabet = list(selfies.get_semantic_robust_alphabet()), I get 69 characters and not 34: 
alphabet_69 =  ['[#B-1]', '[#B]', '[#Branch1]', '[#Branch2]', '[#Branch3]', '[#C+1]', '[#C-1]', '[#C]', '[#N+1]', '[#N]', '[#O+1]', '[#P+1]', '[#P-1]', '[#P]', '[#S+1]', '[#S-1]', '[#S]', '[=B+1]', '[=B-1]', '[=B]', '[=Branch1]', '[=Branch2]', '[=Branch3]', '[=C+1]', '[=C-1]', '[=C]', '[=N+1]', '[=N-1]', '[=N]', '[=O+1]', '[=O]', '[=P+1]', '[=P-1]', '[=P]', '[=Ring1]', '[=Ring2]', '[=Ring3]', '[=S+1]', '[=S-1]', '[=S]', '[B+1]', '[B-1]', '[B]', '[Br]', '[Branch1]', '[Branch2]', '[Branch3]', '[C+1]', '[C-1]', '[C]', '[Cl]', '[F]', '[H]', '[I]', '[N+1]', '[N-1]', '[N]', '[O+1]', '[O-1]', '[O]', '[P+1]', '[P-1]', '[P]', '[Ring1]', '[Ring2]', '[Ring3]', '[S+1]', '[S-1]', '[S]']

Why is it different?

When I configure the semantic constraints of the 4 elements H,O,C,Cl like this:
sf.set_semantic_constraints(bond_constraints={'H': 1, 'Cl': 1, 'O': 2, 'O+1': 0, 'O-1': 1, 'C': 4, 'C+1': 3, 'C-1': 3, '?': 0})
I generate this 33 character alphabet: 
alphabet_33 = ['[#C]', '[P]', '[=Ring1]', '[C+1]', '[Ring1]', '[#Branch3]', '[C-1]', '[C]', '[Cl]', '[O-1]', '[#Branch1]', '[=C]', '[Ring2]', '[Branch2]', '[S]', '[=O]', '[=N]', '[Branch3]', '[N]', '[=C+1]', '[H]', '[Ring3]', '[O]', '[#C+1]', '[=Branch1]', '[=Branch2]', '[Branch1]', '[#C-1]', '[=Branch3]', '[=Ring3]', '[=C-1]', '[=Ring2]', '[#Branch2]']

Nevertheless I observe that there are [P] and [S] characters.
Did I do something wrong?

Thank you for your help,
Lydia

**Comment by akshat998** [comment]
Hi Lydia, 
1. You are correct. there are 69 characters, not 34. 
2. Based on the documentation for `set_semantic_constraints` (https://pypi.org/project/selfies/), it is meant to be used to modify the the number of bonds a particular atom can form. It does not constrain the number of possible atoms as a whole. Hence, with your above list, [P] & [S] are observed. Did you try my suggestion of modifying the line of code? I.e, setting 
`alphabet = ['[Branch1_3]', '[O]', '[Ring1]', '[Branch3_3]', '[Branch2_2]', '[Branch2_3]', '[Cl]', '[=C]', '[Hexpl]', '[Branch2_1]', '[=O]', '[Branch3_2]', '[Branch1_1]', '[Branch1_2]', '[Ring2]', '[#C]', '[Ring3]']`. Maybe you could provide some background on how you are using the code? 

Regards
Akshat :)
